#cloud-config
users:
  - name: scap_auditor
    groups: sudo, admin
    shell: /bin/bash
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: 
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+59tH9Djp6EcZuk4+6xZjRM5wF6gJT5WP7RjoS6XwWNzAad/0Cl+KapUhwhgN09DbmNQ8ax+7Z6N5KLiNyenQxsLZLo4Jk9LQpg2jL/4WPui34cTtxPYtCIUNnDDFfujetZy0wLRJUFAJsRTu80mEqQ6fAdaGlrwEzAvHtRC/DHmAWQFx2a9gIaYAp4nyaR5qC8bTfAknwZMco6vknI9DhVgwmLbWqdltXYBLQGb5Gpoi2Ki4P+2LUQ+Tiga1isJQFn6yM1LJsJ+qdEsQTQlQSFxjUJFhjlSTn+qK6K6EdCNPBtdBXZaNCQSCVhaTdjkvADxhZCtidboGuM2mEX0A4hwyU1eb++m/W16te3giyw9yzFNBVUXWm4UcC4opPhIJNcmOO37PlmpPFSozQ/EtxDsxBtLYIiyB99FbcIIQdzT3fBtVEH08HR6Vaja/VWx/qg2DyDDXUB9/5zOfOFvALyWjSmXzwOZ+9ABiI0qwX6TXk0S+M35Emj8Mhnt/Tb0= scap_auditor@ATAR_IP
    
package_update: true
package_upgrade: true    
packages:
  - unzip
  - libopenscap8
  - ssg-debderived

runcmd:
  - cd /usr/share/xml/scap/ssg/content
  - wget https://github.com/ComplianceAsCode/content/releases/download/v0.1.69/scap-security-guide-0.1.69.zip
  - unzip scap-security-guide-0.1.69.zip
  - cd scap-security-guide-0.1.69/
  - oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --report report.html ssg-ubuntu2004-ds-1.2.xml

# Secure copy results file from remote to local
# scp ubuntu@10.1.29.82:/usr/share/xml/scap/ssg/content/scap-security-guide-0.1.69/report.html ~/Development
